const data = {
    products: [
        {
            name:"Free Shirt",
            category:'Shirts',
            image:'/images/shirt1.jpg',
            price:70,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            countInStock:20,
            description:'Desinershirs arount town',
        },
        {
            name:"Fit Shirt",
            category:'Shirts',
            image:'/images/shirt2.jpg',
            price:40,
            brand:'Polo',
            rating:4.5,
            numReviews:4,
            countInStock:40,
            description:'Arount town',
        },
        {
            name:"Slim Shirt",
            category:'Shirts',
            image:'/images/shirt3.jpg',
            price:10,
            brand:'Zara',
            rating:5,
            numReviews:5,
            countInStock:220,
            description:'Desinershirs around town',
        },
        {
            name:"Golf Pants",
            category:'Pants',
            image:'/images/pants1.jpg',
            price:70,
            brand:'Raymond',
            rating:4.5,
            numReviews:10,
            countInStock:20,
            description:'Smart and cool',
        },
        {
            name:"Fit Pants ",
            category:'Pants',
            image:'/images/pants2.jpg',
            price:80,
            brand:'Zara',
            rating:4.5,
            numReviews:10,
            countInStock:20,
            description:'Popular pants',
        },
        {
            name:"Classic pants",
            category:'Pants',
            image:'/images/pants3.jpg',
            price:110,
            brand:'Casely',
            rating:4.5,
            numReviews:10,
            countInStock:20,
            description:'Desiner pants in town',
        },
    ],
};

export default data;